# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_D_ell <- function(D_e, V, delta, tau_ell, r, a0, a1, p, q, H_bar, mu) {
    .Call('forcedMigration_get_D_ell', PACKAGE = 'forcedMigration', D_e, V, delta, tau_ell, r, a0, a1, p, q, H_bar, mu)
}

get_Dstar <- function(D_e, V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n) {
    .Call('forcedMigration_get_Dstar', PACKAGE = 'forcedMigration', D_e, V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n)
}

get_migration_eq <- function(V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n) {
    .Call('forcedMigration_get_migration_eq', PACKAGE = 'forcedMigration', V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n)
}

get_surplus <- function(V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n, gamma, beta, alpha) {
    .Call('forcedMigration_get_surplus', PACKAGE = 'forcedMigration', V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n, gamma, beta, alpha)
}

get_surplus_infeas <- function(V_tilde, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n, gamma, beta, alpha) {
    .Call('forcedMigration_get_surplus_infeas', PACKAGE = 'forcedMigration', V_tilde, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, mu, omega_n, gamma, beta, alpha)
}

