# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_Dstar <- function(D_e, V, m0, m1, tau_ell, tau_n, r, u_bar, a0, a1, p, q, H, delta, omega_n) {
    .Call('forcedMigration_get_Dstar', PACKAGE = 'forcedMigration', D_e, V, m0, m1, tau_ell, tau_n, r, u_bar, a0, a1, p, q, H, delta, omega_n)
}

get_migration_eq <- function(V, m0, m1, tau_ell, tau_n, r, u_bar, a0, a1, p, q, H, delta, omega_n) {
    .Call('forcedMigration_get_migration_eq', PACKAGE = 'forcedMigration', V, m0, m1, tau_ell, tau_n, r, u_bar, a0, a1, p, q, H, delta, omega_n)
}

get_surplus <- function(V, m0, m1, tau_ell, tau_n, r, u_bar, a0, a1, p, q, H, delta, omega_n, gamma, beta) {
    .Call('forcedMigration_get_surplus', PACKAGE = 'forcedMigration', V, m0, m1, tau_ell, tau_n, r, u_bar, a0, a1, p, q, H, delta, omega_n, gamma, beta)
}

