# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_Dstar <- function(D_e, V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n) {
    .Call('forcedMigration_get_Dstar', PACKAGE = 'forcedMigration', D_e, V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n)
}

get_migration_eq <- function(V, start, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n) {
    .Call('forcedMigration_get_migration_eq', PACKAGE = 'forcedMigration', V, start, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n)
}

get_migration_cum <- function(V_cum, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n) {
    .Call('forcedMigration_get_migration_cum', PACKAGE = 'forcedMigration', V_cum, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n)
}

get_surplus <- function(V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n, gamma, alpha) {
    .Call('forcedMigration_get_surplus', PACKAGE = 'forcedMigration', V, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n, gamma, alpha)
}

get_surplus_infeas <- function(V_tilde, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n, gamma, alpha) {
    .Call('forcedMigration_get_surplus_infeas', PACKAGE = 'forcedMigration', V_tilde, delta, tau_ell, tau_n, r, a0, a1, p, q, H_bar, omega_n, gamma, alpha)
}

get_X_max <- function(tau_ell, r, a0, a1, p, q, H_bar, omega_n) {
    .Call('forcedMigration_get_X_max', PACKAGE = 'forcedMigration', tau_ell, r, a0, a1, p, q, H_bar, omega_n)
}

